spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/quentin-zhang/spring-cloud-demo/config-upper
          search-paths: respo
          username:
          password:
      label: master
server:
  port: 8888


